### ISSUE TITLE
Fix CompatHelper

### ISSUE THREAD

**Issue by ablaom** [ablaom/TumorGrowth.jl#49]
Updated  the ssh keys and the yml file but still can't get CompatHelper to work:

```
{"message":"GitHub Actions is not permitted to create or approve pull requests.","documentation_url":"https://docs.github.com/rest/pulls/pulls#create-a-pull-request","status":"403"}""", HTTP.Exceptions.StatusError(403, "POST", "https://api.github.com/repos/ablaom/TumorGrowth.jl/pulls", HTTP.Messages.Response:
[177](https://github.com/ablaom/TumorGrowth.jl/actions/runs/10894216915/job/30230577479#step:6:178)
"""
```

[Full log](https://github.com/ablaom/TumorGrowth.jl/actions/runs/10894216915/job/30230577479#step:6:235)

**Comment by ablaom** [comment]
@DilumAluthge Any chance you can take a look?

**Comment by DilumAluthge** [comment]
Can you go to https://github.com/ablaom/TumorGrowth.jl/settings/actions and scroll down to "Workflow permissions" and post a screenshot of what you see?

**Comment by ablaom** [comment]
Okay, I needed to tick the box which enabled actions to make PR's 😳 

Many thanks @DilumAluthge for the fix and such a prompt response.
